version: '3.9'

name: envybox_prod

services:
  server:
    build:
      context: ./server/vendor/laravel/sail/runtimes/8.2
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP:?}'
    container_name: envybox_prod_server
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    expose: 
      - 80
    depends_on:
      - db
    environment:
      WWWUSER: '${WWWUSER:?}'
      LARAVEL_SAIL: 1
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
    volumes:
      - './server:/var/www/html'
      - './configs/server/.env:/var/www/html/.env'

  nginx:
    image: nginx
    restart: "no"
    container_name: envybox_prod_nginx
    ports:
      - ${DOCKER_PORT:-80}:80
    depends_on:
      - server
    environment:
      DB_PORT: ${DB_PORT:?}
    volumes:
      - ./client/dist:/usr/share/nginx/html
      - /etc/localtime:/etc/localtime:ro
      - ./nginx/prod:/etc/nginx/conf.d  
  db:
    container_name: envybox_prod_db
    image: mysql:5.5
    restart: unless-stopped
    ports:
      - ${DB_PORT:?}:3306
    volumes:
      - ./mysql/prod:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:?}
      MYSQL_USER: ${DB_USERNAME:?}
      MYSQL_PASSWORD: ${DB_PASSWORD:?}
      MYSQL_DATABASE: ${DB_DATABASE:?}

